Ver1
EestiChameleon/GOphermart pull request #1
Opened 2022-04-12 16:44 UTC by EestiChameleon

test

2022-04-28 19:27 UTC, Barugoo commented on cmd/gophermart/main.go
> +	}
Для отладки это ОК, но в продакшн так релизиться нельзя, если в конфиге адреса нет - приложение должно падать

2022-04-28 19:27 UTC, Barugoo commented on cmd/gophermart/main.go
> +	go service.PollOrderCron(accrual.AccrualBot, time.Second*1)
Давай сделаем период крона конфигурируемым

2022-04-28 19:28 UTC, Barugoo commented on internal/app/cfg/config.go
> +	CryptoKey      string `env:"CRYPTO_KEY" envDefault:"secret_123456789"`                                                  // secret word to encrypt/decrypt JWT for cookies
Давай уберем значение по умолчанию для ключа

2022-04-28 19:30 UTC, Barugoo commented on internal/app/router/handlers/user_balance_withdraw.go
> +	}
Кажется, что вот это все лучше утащить на слой service
Хэндлеры не должны уметь это делать -> если захотим переехать на условный gRPC придется отсюда этот код утаскивать уже туда. Пусть сразу в service будет

2022-04-28 19:31 UTC, Barugoo commented on internal/app/router/handlers/user_balance_withdraw.go
> +	// разрешено ли списывать бонусы в счет уплаты
Лучше на англицком

2022-04-28 19:32 UTC, Barugoo commented on internal/app/router/handlers/user_login.go
> +	}
Тоже будто бы можно утащить этот кусок в слой service, а из него возвращать только токен и ошибку

2022-04-28 19:33 UTC, Barugoo commented on internal/app/router/router.go
> +	router.With(mw.AuthCheck).Get("/api/user/balance/withdrawals", h.UserBalanceWithdrawals)
Давай сгрупперуем хэндлеры по признаку необходимости авторизации, чтобы не прописывать для каждого `With(mw.AuthCheck)`

2022-04-28 19:36 UTC, Barugoo commented on internal/app/service/methods/users.go
> +	}
Давай уменьшать вложенность:
```go
if err != nil && !errors.Is(err, pgx.ErrNoRows) {
    return err
}
if errors.Is(err, pgx.ErrNoRows) {
    return db.ErrNotFound
}

2022-04-28 19:37 UTC, Barugoo commented on migration/sqlscripts/01_db_tables.down.sql
> +DROP TYPE IF EXISTS STATS CASCADE;
Лучше кста не использовать CASCADE, а то мало ли

2022-04-28 19:37 UTC, Barugoo requested changes
Очень хорошо, но давай утащим бизнес-логику из хэндлеров на уровень `service` - и будет просто супер

2022-04-30 09:34 UTC, Barugoo approved these changes
Работу принимаю, супер

2022-04-30 09:35 UTC, EestiChameleon commented
спасибо!

2022-04-30 09:35 UTC, merged